#!/bin/bash
# SPDX-License-Identifier: zlib-acknowledgement
set -e

shopt -s extglob dotglob

mkdir -p build

pushd code

make

mv !(*.[ch]|Makefile) ../build

popd

#pushd run
#../build/connector
#popd
